# Generated by Django 5.0.6 on 2024-06-25 10:30

from django.db import migrations
from api.models import Vulyciperedmist
pidbirtsilist =[
     'Глинянський тракт вул.',
     'Залізнична вул.',
     'Зелена вул.',
     'Злуки вул.',
     'Київська вул.',
     'Козацька вул.',
     'Лесі Українки вул.',
     'Франка вул.',
     'Тиха вул.'

]



def create_pidbirtsilist(apps,schema_editor):
        
        for v in pidbirtsilist:  
            np = Vulyciperedmist(name = v, idperedmistia=3)
            np.save()
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240625_1224'),
    ]

    operations = [
         migrations.RunPython(create_pidbirtsilist),
    ]
