# Generated by Django 5.0.6 on 2024-06-24 17:31

from django.db import migrations
from api.models import Naselenyipunktperedmistia
naspuntkperedmistialist = [

    'Винники',
    'Лисиничі',
    'Підбірці',
    'Волиця',
    'Бережани',
    'Давидів',
    'Пасіки Зубрецькі',
    'Зубра',
    'Мелечковичі',
    'Сокільники',
    'Солонка',
    'Нагоряни',
    'Наварія',
    'Скнилів',
    'Басівка',
    'Годовиця',
    'Лапаївка',
    'Зимна Вода',
    'Рудно',
    'Паланки',
    'Підрясне',
    'Кожичі',
    'Бірки',
    'Брюховичі',
    'Малехів',
    'Муроване',
    'Дубляни',
    'Гамаліівка',
    'Сороки Львівські',
    'інший населений пункт',


]

# def create_naspuntkperedmistia(apps,schema_editor):
        
#         for punktperedmistia in naspuntkperedmistialist:  
#             np = Naselenyipunktperedmistia(name = punktperedmistia)
#             np.save()
class Migration(migrations.Migration):

    dependencies = [
        # ('api', '0001_initial'),
    ]

    operations = [
            # migrations.RunPython(create_naspuntkperedmistia),
    ]
    